[2025-04-11 05:25:11 +0000] [29275] [INFO] Starting gunicorn 23.0.0
[2025-04-11 05:25:11 +0000] [29275] [INFO] Listening at: http://0.0.0.0:5000 (29275)
[2025-04-11 05:25:11 +0000] [29275] [INFO] Using worker: sync
[2025-04-11 05:25:11 +0000] [29324] [INFO] Booting worker with pid: 29324
[2025-04-11 05:25:11 +0000] [29327] [INFO] Booting worker with pid: 29327
[2025-04-11 05:25:11 +0000] [29330] [INFO] Booting worker with pid: 29330
[2025-04-11 05:25:11 +0000] [29335] [INFO] Booting worker with pid: 29335
[2025-04-11 05:26:57 +0000] [29275] [CRITICAL] WORKER TIMEOUT (pid:29335)
[2025-04-11 05:26:57 +0000] [29335] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-11 05:26:57 +0000] [29335] [INFO] Worker exiting (pid: 29335)
[2025-04-11 05:26:57 +0000] [29481] [INFO] Booting worker with pid: 29481
[2025-04-11 05:29:11 +0000] [29275] [INFO] Handling signal: int
[2025-04-11 05:29:11 +0000] [29327] [INFO] Worker exiting (pid: 29327)
[2025-04-11 05:29:11 +0000] [29330] [INFO] Worker exiting (pid: 29330)
[2025-04-11 05:29:11 +0000] [29324] [INFO] Worker exiting (pid: 29324)
[2025-04-11 05:29:11 +0000] [29481] [INFO] Worker exiting (pid: 29481)
[2025-04-11 05:29:11 +0000] [29275] [INFO] Shutting down: Master
[2025-04-11 05:29:48 +0000] [29622] [INFO] Starting gunicorn 23.0.0
[2025-04-11 05:29:48 +0000] [29622] [INFO] Listening at: http://0.0.0.0:5001 (29622)
[2025-04-11 05:29:48 +0000] [29622] [INFO] Using worker: sync
[2025-04-11 05:29:48 +0000] [29623] [INFO] Booting worker with pid: 29623
[2025-04-11 05:29:48 +0000] [29624] [INFO] Booting worker with pid: 29624
[2025-04-11 05:29:48 +0000] [29625] [INFO] Booting worker with pid: 29625
[2025-04-11 05:29:48 +0000] [29626] [INFO] Booting worker with pid: 29626
[2025-04-11 05:37:31 +0000] [29622] [CRITICAL] WORKER TIMEOUT (pid:29623)
[2025-04-11 05:37:31 +0000] [29623] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-11 05:37:31 +0000] [29623] [INFO] Worker exiting (pid: 29623)
[2025-04-11 05:37:31 +0000] [29876] [INFO] Booting worker with pid: 29876
[2025-04-11 05:41:57 +0000] [29622] [INFO] Handling signal: int
[2025-04-11 05:41:57 +0000] [29624] [INFO] Worker exiting (pid: 29624)
[2025-04-11 05:41:57 +0000] [29626] [INFO] Worker exiting (pid: 29626)
[2025-04-11 05:41:57 +0000] [29625] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 274, in parse
    line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 326, in read_line
    self.get_data(unreader, buf)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    time.sleep(0.1)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 199, in handle_quit
    sys.exit(0)
SystemExit: 0
[2025-04-11 05:41:57 +0000] [29625] [INFO] Worker exiting (pid: 29625)
[2025-04-11 05:41:57 +0000] [29876] [INFO] Worker exiting (pid: 29876)
[2025-04-11 05:41:57 +0000] [29622] [INFO] Shutting down: Master
[2025-04-11 05:43:20 +0000] [30112] [INFO] Starting gunicorn 23.0.0
[2025-04-11 05:43:20 +0000] [30112] [INFO] Listening at: http://0.0.0.0:5001 (30112)
[2025-04-11 05:43:20 +0000] [30112] [INFO] Using worker: sync
[2025-04-11 05:43:20 +0000] [30113] [INFO] Booting worker with pid: 30113
[2025-04-11 05:43:20 +0000] [30114] [INFO] Booting worker with pid: 30114
[2025-04-11 05:43:20 +0000] [30115] [INFO] Booting worker with pid: 30115
[2025-04-11 05:43:21 +0000] [30116] [INFO] Booting worker with pid: 30116
